# Numpy

## Dimensions

In [2]:
import numpy as np

In [3]:
# Scalar

scalar = np.array(34)
print(type(scalar))
print(scalar.shape)
print(scalar)

<class 'numpy.ndarray'>
()
34


In [4]:
# Vectors

vector = np.array([34, 27, 45, 33, 22, 19])
print(type(vector))
print("Diemnsion: ",vector.shape)
print(vector)

<class 'numpy.ndarray'>
Diemnsion:  (6,)
[34 27 45 33 22 19]


In [5]:
# Matrix

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(matrix))
print("Diemnsion: ",matrix.shape)
print(matrix)

<class 'numpy.ndarray'>
Diemnsion:  (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Tensor

tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(type(tensor))
print("Diemnsion: ",tensor.shape)
print(tensor)

<class 'numpy.ndarray'>
Diemnsion:  (3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [7]:
# Array creation with arange

array_arange = np.arange(0, 10, 1) # start, stop, step
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Array creation with eye

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# Array creation with diagonals

diagonal_matrix = np.diag([1, 2, 3, 4, 5])
print(diagonal_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [10]:
# Random Array

random_array = np.random.random(5)
print(random_array)

[0.23700731 0.06937934 0.79235978 0.16192821 0.27495077]


In [11]:
# Array sum

array_sum = np.sum([1, 2, 3, 4, 5])
print(array_sum)

15


In [12]:
# array mean

array_mean = np.mean([1, 2, 3, 4, 5])
print(array_mean)

3.0


In [13]:
# array standard deviation  (std)

array_std = np.std([1, 2, 3, 4, 5])
print(array_std)

1.4142135623730951


In [14]:
# Sum Matrix

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

sum = A + B

print(sum)

[[ 6  8]
 [10 12]]


In [15]:
dot_product = np.dot(A, B)
print(dot_product)

[[19 22]
 [43 50]]


In [16]:
a_transpose = A.T
print(a_transpose)

[[1 3]
 [2 4]]


In [17]:
determinant = np.linalg.det(A)
print(determinant)

-2.0000000000000004


In [18]:
inverse = np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [20]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print(X)

[0.  0.5]


In [21]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
